// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eazevyxcentxotdbjzjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhemV2eXhjZW50eG90ZGJqemp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTE3OTQsImV4cCI6MjA3NDE4Nzc5NH0.dIeb99wpJfF51Y22Ir6VoLA_FklRFf9wCnNMQu-zMmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});